#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

plugin-install () {
    NGINX_CONF="/etc/nginx/nginx.conf"
    cat >> $NGINX_CONF << EOF
stream {
    include /home/dokku/*/nginx-stream.conf;
}
EOF
}

plugin-install "$@"