#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/nginx-stream/functions"

trigger-nginx-stream-post-deploy() {
  declare desc="nginx-stream post-deploy plugin trigger"
  declare trigger="nginx_stream_core_post_deploy"
  declare APP="$1"

  if [[ "$(plugn trigger proxy-type "$APP")" == "nginx" ]]; then
    nginx_stream_build_config "$APP"
  fi
}

trigger-nginx-stream-post-deploy "$@"